### PR TITLE
Markdown example

### PR DESCRIPTION
**Pull request by mb720**
Hi!

I'd like to contribute an example that uses [marked](https://github.com/chjj/marked) to convert Markdown text to HTML in the browser using JSweet.

I've added a new index.html in webapp/markdown. The Java file being transpiled to JavaScript is examples/markdown/MarkdownExample.java.

I had to comment out ToDos.java since it wouldn't compile.

I took the liberty to adapt build.gradle so we can use the Gradle wrapper now. The instructions for trying out the examples thus become:
1. `git clone https://github.com/cincheo/jsweet-examples.git`
2. `cd jsweet-examples`
3. `./gradlew jsweet` (Gradle is _not_ required to be installed)
4. Open the desired index.html in the webapp directory with the browser of your choice

### CODE REVIEW

**Comment by lgrignon** [comment]
Nice example. Thanks.

**Comment by renaudpawlak** [comment]
So, you managed to fix the issue in the web browser?
Github says there is a conflict... maybe you should try to sync your repo and submit again the PR. Normally I have fixed the backbone example... maybe the conflict comes from it?

**Comment by mb720** [comment]
Thanks!

I'll sync with the repo and make another PR this week or the next (I'm a bit busy at the moment).

What issue in the web browser are you referring to, @renaudpawlak?

**Comment by mb720** [comment]
Thanks for fixing ToDos.java, Renaud!
I merged my changes with yours.

I removed this comment from ToDos.java since I think it doesn't apply anymore:

```
    // TODO: the Store class in backbone does not define any parameter in the
    // constructor... maybe a mistake in the original TypeScript exammle, which
    // declare the Store class as an "any" variable...
    // Store localStorage = new Store("todos-backbone");
```

**Comment by renaudpawlak** [comment]
Thank you very much. I merged and I will check later if it works well.

**Pull request merged**
